name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: archlinux-latest

    steps:
    - uses: actions/checkout@v6

    - name: Update repos
      run: sudo pacman -Syu libseccomp

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
